runtime: nodejs10
env_variables:
  SQL_USER: root
  SQL_PASSWORD: 12345678
  SQL_DATABASE: shoppingapp
  INSTANCE_CONNECTION_NAME: assignment-two-server:us-central1:serverdatabaseinstance
beta_settings:
  cloud_sql_instances: assignment-two-server:us-central1:serverdatabaseinstance