runtime: nodejs
env: flex
env_variables:
  SQL_USER: tanzim
  SQL_PASSWORD: 12345678
  SQL_DATABASE: ServerDatabase
  INSTANCE_CONNECTION_NAME: assignment-two-server:us-central1:cca2database
beta_settings:
  cloud_sql_instances: assignment-two-server:us-central1:cca2database